---
base_path: "/search/advanced"
content_id: 3df77dea-00c5-43f0-8f31-d08b8bd2a4d6
content_purpose_document_supertype: navigation
document_type: search
locale: en
name: Advanced search
phase: live
publishing_app: rummager
rendering_app: finder-frontend
schema_name: finder
search_user_need_document_supertype: government
title: Latest on GOV.UK
update_type: minor
details:
  document_noun: result
  reject:
    content_store_document_type:
    - browse
  show_summaries: true
  facets:
  - filter_key: content_purpose_subgroup
    key: subgroup
    name: Publication type
    type: text
    preposition: in
    display_as_result_metadata: false
    filterable: true
    allowed_values: []
  - key: public_timestamp
    name: Publication date
    type: date
    preposition: published
    display_as_result_metadata: true
    filterable: true
  - filter_key: part_of_taxonomy_tree
    key: topic
    name: Taxonomy
    type: hidden
    preposition: ''
    display_as_result_metadata: true
    filterable: true
    allowed_values: []
  - filter_key: content_purpose_supergroup
    key: group
    name: Content purpose supergroup
    type: hidden
    preposition: ''
    display_as_result_metadata: false
    filterable: true
    allowed_values: []
  - filter_key: organisations
    key: organisations
    name: Organisations
    type: hidden
    preposition: ''
    display_as_result_metadata: false
    filterable: true
    allowed_values: []
  default_documents_per_page: 20
routes:
- path: "/search/advanced"
  type: exact
- path: "/search/advanced.json"
  type: exact
