---
base_path: "/all-content"
content_id: dd395436-9b40-41f3-8157-740a453ac972
document_type: finder
locale: en
publishing_app: rummager
rendering_app: finder-frontend
schema_name: finder
title: All content
description: Find content from government
signup_content_id: 49838f97-5d2e-407a-8876-30c4abe2a6bc
details:
  default_documents_per_page: 20
  document_noun: result
  format_name: Documents
  reject:
    content_purpose_supergroup:
    - other
  facets:
  - key: "_unused"
    display_as_result_metadata: false
    filter_key: all_part_of_taxonomy_tree
    filterable: true
    keys:
    - level_one_taxon
    - level_two_taxon
    name: topic
    preposition: about
    short_name: topic
    type: taxon
  - display_as_result_metadata: true
    filterable: true
    key: organisations
    name: Organisation
    preposition: from
    short_name: From
    type: text
  - display_as_result_metadata: false
    filterable: true
    key: people
    name: Person
    preposition: from
    type: text
  - display_as_result_metadata: true
    filterable: true
    key: world_locations
    name: World location
    preposition: in
    type: text
  - display_as_result_metadata: true
    filterable: true
    key: public_timestamp
    name: Updated
    short_name: Updated
    type: date
  show_summaries: true
  sort:
  - key: "-popularity"
    name: Most viewed
  - key: "-relevance"
    name: Relevance
  - default: true
    key: "-public_timestamp"
    name: Updated (newest)
  - key: public_timestamp
    name: Updated (oldest)
routes:
- path: "/all-content"
  type: exact
- path: "/all-content.atom"
  type: exact
- path: "/all-content.json"
  type: exact
