---
base_path: "/all-content/email-signup"
content_id: 49838f97-5d2e-407a-8876-30c4abe2a6bc
document_type: finder_email_signup
locale: en
publishing_app: rummager
rendering_app: finder-frontend
schema_name: finder_email_signup
title: All content
description: You'll get an email when content is published.
details:
  email_filter_by:
  email_filter_name:
  subscription_list_title_prefix: 'All content'
  reject:
    content_purpose_supergroup: other
  email_filter_facets:
  - facet_id: people
    facet_name: people
  - facet_id: organisations
    facet_name: organisations
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
routes:
- path: "/all-content/email-signup"
  type: exact
