---
base_path: "/services"
content_id: f6d779ac-5f78-413d-a1ff-da391944e6ec
description: Find services from government
signup_content_id: e72eda7d-8fff-498f-b0f4-c07d8cd8ceb5
details:
  default_documents_per_page: 20
  document_noun: service
  facets:
  - key: "_unused"
    filter_key: all_part_of_taxonomy_tree
    keys:
    - level_one_taxon
    - level_two_taxon
    name: topic
    short_name: topic
    type: taxon
    display_as_result_metadata: false
    filterable: true
    preposition: about
  - display_as_result_metadata: true
    filterable: true
    key: organisations
    name: Organisation
    preposition: from
    short_name: From
    type: text
  filter:
    content_purpose_supergroup:
    - services
  show_summaries: true
  sort:
  - key: title
    name: A-Z
  - default: true
    key: "-popularity"
    name: Most viewed
  - key: "-relevance"
    name: Relevance
document_type: finder
locale: en
publishing_app: rummager
rendering_app: finder-frontend
schema_name: finder
title: Services
routes:
- path: "/services"
  type: exact
- path: "/services.atom"
  type: exact
- path: "/services.json"
  type: exact
