---
base_path: "/search/research-and-statistics/email-signup"
content_id: 119db584-0ae7-45e4-8f3a-fd79316c6921
document_type: finder_email_signup
locale: en
publishing_app: rummager
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Research and statistics
description: <p>You can't subscribe to get email notifications about upcoming statistics.</p><p>Subscribe to published statistics to get an email every time statistics are published or updated.</p>
details:
  email_filter_by:
  email_filter_name:
  subscription_list_title_prefix: Statistics
  filter: {}
  email_filter_facets:
  - facet_id: content_store_document_type
    facet_name: Research and statistics
    facet_choices:
    - key: statistics_published
      filter_values:
      - statistics
      - national_statistics
      - statistical_data_set
      - official_statistics
      radio_button_name: Statistics (published)
      topic_name: Statistics (published)
      prechecked: false
    - key: research
      filter_values:
      - dfid_research_output
      - independent_report
      - research
      radio_button_name: Research
      topic_name: Research
      prechecked: false
  - facet_id: organisations
    facet_name: organisations
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
routes:
- path: "/search/research-and-statistics/email-signup"
  type: exact
