---
base_path: "/find-eu-exit-guidance-business/email-signup"
content_id: 2818d67a-029a-4899-a438-a543d5c6a20d
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Find EU Exit guidance for your business
description: You'll get an email each time EU Exit guidance is published.
details:
  email_filter_by: appear_in_find_eu_exit_guidance_business_finder
  email_filter_name: appear_in_find_eu_exit_guidance_business_finder
  email_signup_choice:
  - key: "yes"
    radio_button_name: "yes"
    topic_name: "appear in find eu exit guidance business finder"
    prechecked: true
  subscription_list_title_prefix: 'Find EU Exit guidance for your business'
routes:
- path: "/find-eu-exit-guidance-business/email-signup"
  type: exact
