---
#
# NOTE: This is a development copy of the find-eu-exit-guidance-business finder config
# See https://github.com/alphagov/govuk-app-deployment-secrets/blob/master/shared_config/find-eu-exit-guidance-business.yml
# for deployment config.
#
base_path: "/find-eu-exit-guidance-business"
content_id: 42ce66de-04f3-4192-bf31-8394538e0734
signup_content_id: 2818d67a-029a-4899-a438-a543d5c6a20d
title: Find EU Exit guidance for your business
description: 'This is the information that has been published so far for your business to prepare for EU exit. You can change what information you get using the checkboxes. Come back to this page regularly or sign up to receive emails when new information is published.'
name: 'Find EU Exit guidance for your business'
locale: en
public_updated_at: '2018-11-23T09:00:00.000+00:00'
publishing_app: rummager
rendering_app: finder-frontend
details:
  beta: false
  document_noun: publication
  summary: 'This is the information that has been published so far for your business to prepare for EU exit. You can change what information you get using the checkboxes. Come back to this page regularly or sign up to receive emails when new information is published.'
  canonical_link: true
  sort:
    - name: Topic
      key: topic
      default: true
    - name: Most viewed
      key: -popularity
    - name: Relevance
      key: -relevance
    - name: Most recent
      key: -public_timestamp
    - name: A to Z
      key: title
  filter:
    appear_in_find_eu_exit_guidance_business_finder: "yes"
  facets:
  - allowed_values:
    - label: Accommodation
      value: accommodation
    - label: Aerospace
      value: aerospace
    - label: Agriculture and forestry (including wholesale)
      value: agriculture
    - label: Air freight and air passenger services
      value: air-freight-air-passenger-services
    - label: Arts, culture and heritage
      value: arts-culture-heritage
    - label: Automotive
      value: automotive
    - label: Auxiliary activities
      value: auxiliary-activities
    - label: Media and broadcasting
      value: broadcasting
    - label: Charities
      value: charities
    - label: Chemicals
      value: chemicals
    - label: Clothing and consumer goods
      value: clothing-consumer-goods
    - label: Clothing and consumer goods manufacture
      value: clothing-consumer-goods-manufacturing
    - label: Construction
      value: construction-contracting
    - label: Digital, technology and computer services
      value: computer-services
    - label: Creative industries
      value: creative-industries
    - label: Defence
      value: defence
    - label: Education
      value: education
    - label: Electricity
      value: electricity
    - label: Electronics, parts and machinery
      value: electronics-parts-machinery
    - label: Environmental services
      value: environmental-services
    - label: Financial services
      value: financial-services
    - label: Fisheries (including wholesale)
      value: fisheries
    - label: Food, drink and tobacco (retail and wholesale)
      value: food-and-drink
    - label: Food, drink and tobacco (processing)
      value: food-drink-tobacco
    - label: Furniture manufacture
      value: furniture-manufacture
    - label: Gambling
      value: gambling
    - label: Health and social care services
      value: health-social-care-services
    - label: Installation, servicing and repair
      value: installation-servicing-repair
    - label: Insurance
      value: insurance
    - label: Justice, including prisons
      value: justice-prisons
    - label: Marine
      value: marine
    - label: Marine transport
      value: marine-transport
    - label: Medical technology
      value: medical-technology
    - label: Metals manufacture
      value: metals-manufacture
    - label: Mining
      value: mining
    - label: Motor trade
      value: motor-trades
    - label: Non-metal materials manufacture
      value: non-metal-materials-manufacture
    - label: Nuclear
      value: nuclear
    - label: Oil, gas and coal
      value: oil-gas-coal
    - label: Other advanced manufacturing
      value: other-advanced-manufacturing
    - label: Other energy
      value: other-energy
    - label: Other manufacturing
      value: other-manufacturing
    - label: Personal services
      value: personal-services
    - label: Pharmaceuticals
      value: pharmaceuticals
    - label: Ports and airports
      value: ports-airports
    - label: Postal and courier services
      value: postal-courier-services
    - label: Professional and business services
      value: professional-and-business-services
    - label: Public administration
      value: public-administration
    - label: Rail
      value: rail
    - label: Rail (passengers and freight)
      value: rail-passenger-freight
    - label: Real estate
      value: real-estate-excl-imputed-rent
    - label: Repair of computers and consumer goods
      value: repair-of-computers-consumer-goods
    - label: Research
      value: research
    - label: Restaurants, bars and catering
      value: restaurants-bars-catering
    - label: Retail and wholesale (excluding motor trade, food and drink)
      value: retail
    - label: Road (passengers and freight)
      value: road-passengers-freight
    - label: Space
      value: space
    - label: Sports and recreation
      value: sports-recreation
    - label: Telecoms and information services
      value: telecoms
    - label: Tourism
      value: tourism
    - label: Veterinary
      value: veterinary
    - label: Voluntary and community organisations
      value: voluntary-community-organisations
    - label: Warehouses, services and pipelines
      value: warehouses-services-pipelines
    display_as_result_metadata: true
    filterable: true
    combine_mode: and
    key: sector_business_area
    name: Sector / Business Area
    preposition: your business is in
    type: text
  - allowed_values:
    - label: Sell products or goods in the UK
      value: products-or-goods
    - label: Buy products or goods from abroad
      value: buying
    - label: Sell products or goods abroad
      value: selling
    - label: Do other types of business in the EU
      value: other-eu
    - label: Transport goods abroad
      value: transporting
    display_as_result_metadata: true
    filterable: true
    combine_mode: and
    key: business_activity
    name: Business activity
    preposition: you
    type: text
  - allowed_values:
    - label: "EU citizens"
      value: "yes"
    - label: "No EU citizens"
      value: "no"
    display_as_result_metadata: true
    filterable: true
    combine_mode: or
    key: employ_eu_citizens
    name: Who you employ
    short_name: Employing EU citizens
    preposition: you employ
    type: text
  - allowed_values:
    - label: Processing personal data from Europe
      value: processing-personal-data
    - label: Using websites or services hosted in Europe
      value: interacting-with-eea-website
    - label: Providing digital services available to Europe
      value: digital-service-provider
    display_as_result_metadata: true
    filterable: true
    combine_mode: or
    key: personal_data
    name: Personal data
    preposition: you exchange personal data by
    type: text
  - allowed_values:
    - label: Copyright
      value: copyright
    - label: Trade marks
      value: trademarks
    - label: Designs
      value: designs
    - label: Patents
      value: patents
    - label: Exhaustion of rights
      value: exhaustion-of-rights
    display_as_result_metadata: true
    filterable: true
    combine_mode: or
    key: intellectual_property
    name: Intellectual property
    preposition: you use or rely on
    type: text
  - allowed_values:
    - label: EU funding
      value: receiving-eu-funding
    - label: UK government funding
      value: receiving-uk-government-funding
    display_as_result_metadata: true
    filterable: true
    combine_mode: or
    key: eu_uk_government_funding
    name: EU or UK government funding
    short_name: EU or UK government funding
    preposition: you get
    type: text
  - allowed_values:
    - label: Civil government contracts
      value: civil-government-contracts
    - label: Defence contracts
      value: defence-contracts
    display_as_result_metadata: true
    filterable: true
    combine_mode: or
    key: public_sector_procurement
    name: Public sector procurement
    preposition: you apply for
    type: text
routes:
- path: "/find-eu-exit-guidance-business"
  type: exact
- path: "/find-eu-exit-guidance-business.atom"
  type: exact
- path: "/find-eu-exit-guidance-business.json"
  type: exact
document_type: finder
schema_name: finder
ordered_related_items:
  - 705ff357-7e3a-49ae-823e-5d6c7078d350
  - e9bf1cbb-fcba-485a-8e1b-bf36d195c7b1
  - f026b0f9-ce9c-499a-a3cd-1ba9aad8f368
  - b0a8b221-b2cb-434c-abb8-1a7323fd1e05
  - d2c7d17e-adf5-4ea1-b16b-4db9f922190a
  - a5d2f87c-06ae-4cf0-bea7-3fc9746eddd9
  - fae745d3-c5a5-4505-aa59-d257e4e938c1
  - 27952a1b-702d-4166-bd62-6538892f73c3
  - 88ad2f6e-fb1e-47c9-8201-fdb02f90542c
  - 7dd1f3ec-04a9-4954-b7c1-b7fd531daafc
  - b1194956-d0dd-4353-a835-5c4650528e74
  - f896235a-0cf0-4047-af75-926df45e1aa6
  - 1ecf3661-4bf0-4776-9cd6-7ecd5cffac2e
  - 2f6219da-6453-494f-bd5e-2e599642612d
  - 54b2b1e7-68a1-4df9-a9e4-70bcd0bcde71
  - aff1b568-e23b-464b-bd24-5c0a0cd9bf27
  - b7b029ef-a1a5-4d87-9e21-3b7409baf77c
  - 4cc71bfd-4a2b-4bb0-b3b2-de9a9909ab53
  - 7567f8d9-ac09-47ed-aa89-cd51e56d72b1
  - f0dcee7c-97f2-47da-9727-1f4fb1bf0578
  - e5b88fc9-60c5-4747-a9a1-263db349605b
  - 4645a471-468e-4634-be0c-f63668d57626
  - 9aa99522-bab7-4176-811a-82b104710e3f
  - 0246736f-ef09-4d45-ba2d-cd10dc80b82b
  - 5e017fbd-e165-43a1-8a16-57edf9f527b0
