---
tag: search-api.publishing.service.gov.uk
:concurrency: 5
staging:
  :concurrency:  16
production:
  :concurrency:  16
:require: ./lib/rummager.rb
:logfile: ./log/sidekiq.log
:queues:
  - default
  - bulk
:limits:
  bulk: 4
  default: 8
